### ISSUE TITLE
Schema

### ISSUE THREAD

**Issue by PLUCS2** [jessicaUP/WearbyParker#2]
- [x] Mailers (text and email) will not be implemented or will be part of the BONUS - so they will not be on your users table initially 
- [x] I think glasses can be available in multiple sizes. I recommend having a sizes table and a joins table between products and the sizes table so that you can both search by sizes and allow users to see which sizes are available for a certain product. 
- [x] Based on above ^  make everything that is filterable (on the filter search option) its own table with a joins to products
- [x] Size on the Product table and `frame width` on the product cart joins are the same thing. Since frame width will become its own table you can eliminate this as you will be able to access the frame width through the product - or you can store as a foreign key rather than a string included in that collection (this is also true with the try on cart table)

Excellent job! Let me know if you have any questions!

**Comment by jessicaUP** [comment]
Thank you -- Just made the corrections, let me know if there are any other adjustments. 

**one note about color -- they have general color categories (used for filter, I seperated that to its own table) and a color name (that can be anything specific to that pair, I left this on as a column in the products table) 
Is that correct or should I add the name to the color table as well as the category name.

**Comment by PLUCS2** [comment]
Sounds good to me! Nice work!
