### ISSUE TITLE
Sample State 

### ISSUE THREAD

**Issue by PLUCS2** [jessicaUP/WearbyParker#3]
- [x] Will you ever have multiple users in your frontend state? (same goes with addresses and carts) 
- [x] Products can hold a genderId if they are only owned by 1 gender 

This looks awesome! Let me know if you have any questions

**Comment by jessicaUP** [comment]
- No there is only ever one account to deal with at a time, they do not interact with each other.
- There are multiple addresses for one user.
- I have the tryon items and the purchase items go to the same cartId, so there will only ever be one cart. Do you think this the best way to handle that or should I have a seperate cart for the tryon vs purchase? 
- That makes more sense, just updated the schema -- removed gender joins table, added the gender id to the product table, fixed product/gender associations, and fixed up the cart associations.

**Comment by jessicaUP** [comment]
- Just updated the sample state - I removed the extra user/cart example (since there will only one at a time)

Let me know if these changes make more sense.
