### ISSUE TITLE
Routes

### ISSUE THREAD

**Issue by PLUCS2** [jessicaUP/WearbyParker#4]
## Backend 
- [ ] What does this mean? `GET /api/addresses = Returns the user's addresses (filtered by data/params)*`
- [ ] If they only ever show products based on gender than your products index should expect a query string that would specify the gender to send back (yes to your note) 
- [ ] How will you account for a multi-filtered search? 

## Frontend 
Nice work! This looks good. 

Let me know if you have any questions!

**Comment by jessicaUP** [comment]
- `GET /api/addresses = Returns the user's addresses (filtered by data/params)*` :
      - There are multiple addresses per user.  
      - For the user to see all of their listed addresses, thinking it would be filtered by the user's id. So it would just show the relevant addresses for that account. Example below
![Screen Shot 2021-05-09 at 4 28 07 PM](https://user-images.githubusercontent.com/79214086/117586034-b96e2400-b0e3-11eb-8919-def247e5bd89.png)
- is there a better way for me to do this?

**Comment by jessicaUP** [comment]
- For the products could I just have `GET /api/products` with the filtering handled with the query string?

**Comment by jessicaUP** [comment]
Just updated the backend routes, am I over simplifying it for the filtering?
